python main.py burger \
                    --tag burger1D_siren_omega0_5_lr_0.00001_hidden_3_features_128_harmonics_3\
                    --init_cond example1 \
                    --num_hidden_layers 4 \
                    --hidden_features 128 \
                    --network siren \
                    -sr 4000 \
                    --dt 0.005 \
                    -T 150 \
                    --lr 0.00001\
                    -g 0 \
                    --omega_0 15
