python main.py fluid \
    --tag many_times_test \
    --init_cond taylorgreen_multi \
    --num_hidden_layers 1 \
    --hidden_features 128 \
    --config_tcn_path configs_hash/config_hash.json \
    --network hashgrid \
    --nonlinearity relu \
    -sr 128 \
    -vr 32 \
    --dt 0.05 \
    --max_n_iters 500 \
    --max_n_iters_inic 500 \
    -T 100 \
    -g 0