python main.py fluid \
    --tag sanity_test_res_json_hash \
    --init_cond taylorgreen_multi \
    --num_hidden_layers 2 \
    --hidden_features 128 \
    --config_tcn_path configs_hash/config_hash.json \
    --network hashgrid \
    --nonlinearity relu \
    --lr 0.01 \
    -sr 1024 \
    -vr 32 \
    --dt 0.05 \
    -T 0 \
    --max_n_iters 1000 \
    --max_n_iters_inic 1000 \
    -g 0